/**
 * OFFICIAL CHANNEL PARTNER DIRECTORY — NSFDC & PM-SURAJ ECOSYSTEM
 *
 * Sourced directly from official Government of India channel partner frameworks (NSFDC Partner Registry 2026).
 * Contains 91 verified channel partners across SCAs, PSBs, RRBs, NBFC-MFIs, SFBs, Cooperative Banks & Societies.
 */

import type { ChannelPartner } from '@/types/partner';

export const DEMO_PARTNERS: ChannelPartner[] = [
  {
    "id": "streenidhi",
    "name": "Streenidhi",
    "type": "Cooperative Societies",
    "shortType": "Coop Society",
    "state": "Telangana",
    "district": "Hyderabad",
    "address": "401 & 402, 4th Floor, My Home Sarovar Plaza, Secretariat Road, Ambedkar Colony, Saifabad, Hyderabad, Telangana 500004",
    "latitude": 17.385,
    "longitude": 78.4867,
    "supportedSchemes": [
      "udyam-nidhi",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "streenidhi-ap",
    "name": "Streenidhi AP",
    "type": "Cooperative Societies",
    "shortType": "Coop Society",
    "state": "Andhra Pradesh",
    "district": "Vijayawada",
    "address": "2nd Floor, NTR Administrative Block, RTC Complex, Vijayawada-520013, Andhra Pradesh",
    "latitude": 16.5062,
    "longitude": 80.648,
    "supportedSchemes": [
      "udyam-nidhi",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "shri-mahila-sewa-sahakari-bank-ltd",
    "name": "Shri Mahila Sewa Sahakari Bank Ltd.",
    "type": "Co-operative Banks",
    "shortType": "Coop Bank",
    "state": "Gujarat",
    "district": "Ahmedabad",
    "address": "109, Sakar-II, Opp. Town Hall, Ellisbridge, Ahmedabad-38006",
    "latitude": 23.0225,
    "longitude": 72.5714,
    "supportedSchemes": [
      "udyam-nidhi",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "konoklata-mahila-urban-cooperative-bank",
    "name": "Konoklata Mahila Urban Cooperative Bank",
    "type": "Co-operative Banks",
    "shortType": "Coop Bank",
    "state": "Assam",
    "district": "Guwahati",
    "address": "Assam",
    "latitude": 26.1445,
    "longitude": 91.7362,
    "supportedSchemes": [
      "udyam-nidhi",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "anik-financial-services-private-limited",
    "name": "Anik Financial Services Private Limited",
    "type": "NBFC\u2013Micro Finance Institutions (NBFC-MFIs)",
    "shortType": "NBFC-MFI",
    "state": "Maharashtra",
    "district": "Latur",
    "address": "Regd. Office: Sahyadri Building, Behind Amitesh Hotel, Ambajogai Road, Sai Naka, Latur \u2013 413 512",
    "latitude": 18.4088,
    "longitude": 76.5604,
    "supportedSchemes": [
      "aajeevika",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "grameen-development-finance-private-limited",
    "name": "Grameen Development & Finance Private Limited",
    "type": "NBFC\u2013Micro Finance Institutions (NBFC-MFIs)",
    "shortType": "NBFC-MFI",
    "state": "Assam",
    "district": "Kamrup",
    "address": "Dubjent, Kulshi Road, Chhaygaon, Kamrup, Assam Pin \u2013 781 124",
    "latitude": 26.0467,
    "longitude": 91.3653,
    "supportedSchemes": [
      "aajeevika",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "asa-international-microfinance-ltd",
    "name": "ASA International Microfinance Ltd.",
    "type": "NBFC\u2013Micro Finance Institutions (NBFC-MFIs)",
    "shortType": "NBFC-MFI",
    "state": "West Bengal",
    "district": "Kolkata",
    "address": "Victoria Park, 4th Floor, GN-37/2, Sector-V, Salt Lake City, Kolkata \u2013 700 091, West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "supportedSchemes": [
      "aajeevika",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "midland-microfin-ltd",
    "name": "Midland Microfin Ltd.",
    "type": "NBFC\u2013Micro Finance Institutions (NBFC-MFIs)",
    "shortType": "NBFC-MFI",
    "state": "Punjab",
    "district": "Jalandhar",
    "address": "The Axis, Plot No.1, R.B. Badri Dass Colony, BMC Chowk, G.T. Road, Jalandhar \u2013 144 001, Punjab",
    "latitude": 31.326,
    "longitude": 75.5762,
    "supportedSchemes": [
      "aajeevika",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "satin-creditcare-network-ltd",
    "name": "Satin Creditcare Network Ltd.",
    "type": "NBFC\u2013Micro Finance Institutions (NBFC-MFIs)",
    "shortType": "NBFC-MFI",
    "state": "Haryana",
    "district": "Gurugram",
    "address": "Plot No.492, Udyog Vihar, Phase-III, Gurugram, Haryana \u2013 122 016",
    "latitude": 28.4595,
    "longitude": 77.0266,
    "supportedSchemes": [
      "aajeevika",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "pahal-financial-services-pvt-ltd",
    "name": "Pahal Financial Services Pvt. Ltd.",
    "type": "NBFC\u2013Micro Finance Institutions (NBFC-MFIs)",
    "shortType": "NBFC-MFI",
    "state": "Gujarat",
    "district": "Ahmedabad",
    "address": "7th Floor, Binori B Square-2, Opp. Hathising Ni Vadi, Ambli-Iscon Road, Ahmedabad \u2013 380 054, Gujarat",
    "latitude": 23.0285,
    "longitude": 72.5774,
    "supportedSchemes": [
      "aajeevika",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "vector-finance-pvt-ltd",
    "name": "Vector Finance PVT LTD",
    "type": "NBFC\u2013Micro Finance Institutions (NBFC-MFIs)",
    "shortType": "NBFC-MFI",
    "state": "Odisha",
    "district": "Bhubaneswar",
    "address": "RO-K7/110, Ground Floor, Klinga Vihar, P.S. Khandagiri, Bhubaneswar ODISHA-751029",
    "latitude": 20.2961,
    "longitude": 85.8245,
    "supportedSchemes": [
      "aajeevika",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "north-eastern-development-finance-corporation-ltd-nedfi",
    "name": "North Eastern Development Finance Corporation Ltd. (NEDFi)",
    "type": "Other Agencies & SIDBI",
    "shortType": "Other",
    "state": "Assam",
    "district": "Guwahati",
    "address": "Tea Auction Center, GS Rd, Sanket Vihar, Dispur, Opposite, Guwahati, Assam 781006",
    "latitude": 26.1505,
    "longitude": 91.7422,
    "supportedSchemes": [
      "term-loan",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "jharkhand-silk-textile-handicraft-development-corporation-ltd-jharcraft",
    "name": "Jharkhand Silk Textile & Handicraft Development Corporation Ltd. (JHARCRAFT)",
    "type": "Other Agencies & SIDBI",
    "shortType": "Other",
    "state": "Jharkhand",
    "district": "Ranchi",
    "address": "Jharcraft, DIC Campus, Ratu Road, Ranchi, Jharkhand 834001",
    "latitude": 23.3441,
    "longitude": 85.3096,
    "supportedSchemes": [
      "term-loan",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "small-industries-development-bank-of-india-sidbi",
    "name": "Small Industries Development Bank of India (SIDBI)",
    "type": "Other Agencies & SIDBI",
    "shortType": "Other",
    "state": "Uttar Pradesh",
    "district": "Lucknow",
    "address": "SIDBI Tower, 15, Ashok Marg, Lucknow - 226001, Uttar Pradesh",
    "latitude": 26.8467,
    "longitude": 80.9462,
    "supportedSchemes": [
      "term-loan",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "indian-overseas-bank",
    "name": "Indian Overseas Bank",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Tamil Nadu",
    "district": "Chennai",
    "address": "Central Office, 763, Anna Salai, Chennai, Tamil Nadu \u2013 600 002",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "bank-of-baroda",
    "name": "Bank of Baroda",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Gujarat",
    "district": "Vadodara",
    "address": "Baroda Bhavan, 7th Floor, R.C. Dutt Road, Vadodara \u2013 390 007 (Gujarat)",
    "latitude": 22.3072,
    "longitude": 73.1812,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "canara-bank",
    "name": "Canara Bank",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Karnataka",
    "district": "Bengaluru",
    "address": "Head Office, 112, J.C. Road, Bengaluru \u2013 560 002",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "punjab-national-bank",
    "name": "Punjab National Bank",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Delhi",
    "district": "New Delhi",
    "address": "Plot No.-4, Sector 10, Dwarka, New Delhi \u2013 110 075",
    "latitude": 28.6139,
    "longitude": 77.209,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "punjab-sind-bank",
    "name": "Punjab & Sind Bank",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Delhi",
    "district": "New Delhi",
    "address": "Priority Sector Advance Department, 5th Floor, 21 Rajendra Place, New Delhi \u2013 110 008",
    "latitude": 28.6199,
    "longitude": 77.215,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "union-bank-of-india",
    "name": "Union Bank of India",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Maharashtra",
    "district": "Mumbai",
    "address": "Rural & Agri Business Department, Central Office, Union Bank Bhavan Marg, Nariman Point, Mumbai \u2013 400",
    "latitude": 18.922,
    "longitude": 72.8347,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "indian-bank-corporate-office",
    "name": "Indian Bank Corporate Office",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Tamil Nadu",
    "district": "Chennai",
    "address": "No.254-260, Avvai Shanmungam Salai, Gowdi Mutt Road, Royapetta, Chennai \u2013 600 014",
    "latitude": 13.0887,
    "longitude": 80.2767,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "bank-of-maharashtra",
    "name": "Bank of Maharashtra",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Maharashtra",
    "district": "Pune",
    "address": "Head office Lok Mangal, 1501, Shivajinagar, Pune-411005, Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "bank-of-india",
    "name": "Bank of India",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Maharashtra",
    "district": "Mumbai",
    "address": "Bandra Kurla Complex, Bandra (East), Mumbai-400051",
    "latitude": 18.928,
    "longitude": 72.8407,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "central-bank-of-india",
    "name": "Central Bank Of India",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "Maharashtra",
    "district": "Mumbai",
    "address": "Chandermukhi Bldg., Nariman Point, Mumbai \u2013 400 021",
    "latitude": 18.934,
    "longitude": 72.8467,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "uco-bank",
    "name": "UCO Bank",
    "type": "Public Sector Banks (PSBs)",
    "shortType": "PSB",
    "state": "West Bengal",
    "district": "Kolkata",
    "address": "No 3&4, DD Block, Sector-1, Bidhannagar, Kolkata, West Bengal-700064",
    "latitude": 22.5786,
    "longitude": 88.3699,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "bihar-gramin-bank",
    "name": "Bihar Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Bihar",
    "district": "Patna",
    "address": "Shri Vishnu Commercial Complex, NH-30, New Bypass, Near BP Highway Services Petrol Pump, Asochak, Patna - 800016",
    "latitude": 25.5941,
    "longitude": 85.1376,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "maharashtra-gramin-bank",
    "name": "Maharashtra Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Maharashtra",
    "district": "Aurangabad",
    "address": "Plot No.35, Jeewan Shri Town Centre, CIDCO, Aurangabad, Maharashtra \u2013 431 003",
    "latitude": 19.8762,
    "longitude": 75.3433,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "jharkhand-gramin-bank",
    "name": "Jharkhand Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Jharkhand",
    "district": "Ranchi",
    "address": "Zila Parishad Market Complex, 3rd Floor, Kutchery Road, Ranchi-834001, Jharkhand",
    "latitude": 23.3501,
    "longitude": 85.3156,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "haryana-gramin-bank",
    "name": "Haryana Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Haryana",
    "district": "Rohtak",
    "address": "Near Bajrang Bhawan, Delhi Road, Rohtak, Haryana \u2013124 001",
    "latitude": 28.8955,
    "longitude": 76.6066,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "gujarat-gramin-bank",
    "name": "Gujarat Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Gujarat",
    "district": "Bharuch",
    "address": "Head Office, Sky Line Building, 2nd Floor, Near Shital Guest House, Bharuch - 392001, Gujarat",
    "latitude": 21.7051,
    "longitude": 72.9959,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "telangana-grameena-bank",
    "name": "Telangana Grameena Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Telangana",
    "district": "Hyderabad",
    "address": "H.No.2-1-520, 2nd Floor, Vijaya Sri Sai Celestia, Street No.9, Shankermut Road, Nallakunta, Hyderabad, Telangana \u2013 500044",
    "latitude": 17.391,
    "longitude": 78.4927,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "rajasthan-gramin-bank",
    "name": "Rajasthan Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Rajasthan",
    "district": "Jodhpur",
    "address": "Tulsi Tower, 9th B Road, Sardarpura, Jodhpur \u2013 342003 (Rajasthan)",
    "latitude": 26.2389,
    "longitude": 73.0243,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "uttar-pradesh-gramin-bank",
    "name": "Uttar Pradesh Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Uttar Pradesh",
    "district": "Lucknow",
    "address": "2nd & 3rd Floor, NBCC Commercial Complex, Vardan Khand, Gomti Nagar Extension, Lucknow\u2013229001(Uttar Pradesh)",
    "latitude": 26.8527,
    "longitude": 80.9522,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "kerala-grameena-bank",
    "name": "Kerala Grameena Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Kerala",
    "district": "Malappuram",
    "address": "PB No.10, KGpB Towers, AK Road, Uphill, Malappuram, Kerala \u2013 676505",
    "latitude": 11.072,
    "longitude": 76.074,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "uttarakhand-gramin-bank",
    "name": "Uttarakhand Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Uttarakhand",
    "district": "Dehradun",
    "address": "18-New Road, Dehradun, Uttarakhand",
    "latitude": 30.3165,
    "longitude": 78.0322,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "tripura-gramin-bank",
    "name": "Tripura Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Tripura",
    "district": "Agartala",
    "address": "H.O. Airport Road, PO Abhaynagar, Agartala, Tripura (W) Pin \u2013 799 005",
    "latitude": 23.8315,
    "longitude": 91.2868,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "karnataka-grameena-bank",
    "name": "Karnataka Grameena Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Karnataka",
    "district": "Mysuru",
    "address": "Head Office, CA 20, Vijayanagar IInd Stage, Musure \u2013 570017 (Karnataka)",
    "latitude": 12.2958,
    "longitude": 76.6394,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "assam-gramin-bank",
    "name": "Assam Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Assam",
    "district": "Guwahati",
    "address": "HO, G.S. Road, Bhangagarh, Guwahati- 781 005 (Assam)",
    "latitude": 26.1565,
    "longitude": 91.7482,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "andhra-pradesh-grameena-bank",
    "name": "Andhra Pradesh Grameena Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Andhra Pradesh",
    "district": "Guntur",
    "address": "4th Floor, Raghu Mansion, 4-1, Broadipet, Guntur -522 002 (Andhra Pradesh)",
    "latitude": 16.3067,
    "longitude": 80.4365,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "punjab-gramin-bank",
    "name": "Punjab Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Punjab",
    "district": "Kapurthala",
    "address": "HO Jalandhar Road, Kapurthala \u2013 144 601 (Punjab)",
    "latitude": 31.38,
    "longitude": 75.38,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "tamil-nadu-grama-bank",
    "name": "Tamil Nadu Grama Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Tamil Nadu",
    "district": "Salem",
    "address": "6, Yercaud Road, Hasthasmpatti, Salem \u2013 636007 (Tamil Nadu)",
    "latitude": 11.6643,
    "longitude": 78.146,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "madhaya-pradesh-gramin-bank",
    "name": "Madhaya Pradesh Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Madhya Pradesh",
    "district": "Indore",
    "address": "C21, Business Park, C21 Square opposite Hotel Radisson Blue, MR-10, Indore- 452010, Madhaya Pradesh",
    "latitude": 22.7196,
    "longitude": 75.8577,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "himachal-pradesh-gramin-bank",
    "name": "Himachal Pradesh Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Himachal Pradesh",
    "district": "Mandi",
    "address": "Jail Road (Panjethi), PO \u2013 Talyahar, Mandi 175001 (Himachal Pradesh)",
    "latitude": 31.7087,
    "longitude": 76.932,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "puducherry-grama-bank",
    "name": "Puducherry Grama Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Puducherry",
    "district": "Puducherry",
    "address": "No.441, Mahatma Gandhi Road, Muthialpet, Puducherry \u2013 605 003",
    "latitude": 11.9416,
    "longitude": 79.8083,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "west-bengal-gramin-bank",
    "name": "West Bengal Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "West Bengal",
    "district": "Howrah",
    "address": "Natabar Paul Road, Chatterjee Para More, Tikiapara, Howrah \u2013 711101 (WB)",
    "latitude": 22.5958,
    "longitude": 88.2636,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "chhattisgarh-gramin-bank",
    "name": "Chhattisgarh Gramin Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Chhattisgarh",
    "district": "Nava Raipur",
    "address": "Corporate Office Raipur, Plot No.-47, Sector-24, Atal Nagar, Nava Raipur-492013",
    "latitude": 21.161,
    "longitude": 81.7865,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "manipur-rural-bank",
    "name": "Manipur Rural Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Manipur",
    "district": "Imphal",
    "address": "Keishampat, Keisham Leikai, Imphal, Manipur 795001",
    "latitude": 24.817,
    "longitude": 93.9368,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "meghalaya-rural-bank",
    "name": "Meghalaya Rural Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Meghalaya",
    "district": "Shillong",
    "address": "M.T.C Building, 2nd Floor, Police Bazar, Shillong-793001",
    "latitude": 25.5788,
    "longitude": 91.8933,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "j-k-grameen-bank",
    "name": "J&K Grameen Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Jammu & Kashmir",
    "district": "Jammu",
    "address": "Near Fruit Complex, Narwal, Jammu (J&K) -180006",
    "latitude": 32.7266,
    "longitude": 74.857,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "odisha-grameen-bank",
    "name": "Odisha Grameen Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Odisha",
    "district": "Bhubaneswar",
    "address": "7R25-H75, Jagamara, Sunderpada Road, Gandamuda, Pokhhariput, Bhubaneshwar -751030, Odisha",
    "latitude": 20.3021,
    "longitude": 85.8305,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "mizoram-rural-bank",
    "name": "Mizoram Rural Bank",
    "type": "Regional Rural Banks (RRBs)",
    "shortType": "RRB",
    "state": "Mizoram",
    "district": "Aizawl",
    "address": "MINECO, Khatla Aizawl - 796001",
    "latitude": 23.7271,
    "longitude": 92.7176,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "andhra-pradesh-scheduled-castes-cooperative-finance-corporation-ltd-apsccfc",
    "name": "Andhra Pradesh Scheduled Castes Cooperative Finance Corporation Ltd. (APSCCFC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Andhra Pradesh",
    "district": "Amaravathi",
    "address": "SP River View Apartments, 3rd Floor, Tadepalli, Amaravathi \u2013 522 501.",
    "latitude": 16.5131,
    "longitude": 80.5165,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "andhra-pradesh-state-financial-corporation-apsfc",
    "name": "Andhra Pradesh State Financial Corporation (APSFC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Andhra Pradesh",
    "district": "Vijayawada",
    "address": "APSFC Building, Plot OS No.2, 2nd Cross, 3rd Road, Industrial Park, Vijayawada \u2013 520 007.",
    "latitude": 16.5122,
    "longitude": 80.654,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "assam-state-development-corporation-for-scs-ltd-ascdc",
    "name": "Assam State Development Corporation for SCs Ltd. (ASCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Assam",
    "district": "Guwahati",
    "address": "Swahid Dilip Hozori Path, Sarumotoria, Dispur, Guwahati \u2013 781 006.",
    "latitude": 26.1625,
    "longitude": 91.7542,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "bihar-state-scs-co-operative-development-corporation-ltd-bssccdc",
    "name": "Bihar State SCs Co-operative Development Corporation Ltd. (BSSCCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Bihar",
    "district": "Patna",
    "address": "RN-212, Officers Colony (Block-A), Bailey Road, Patna \u2013 800 001.",
    "latitude": 25.6001,
    "longitude": 85.1436,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "chandigarh-scs-bcs-minorities-financial-development-corporation-ltd-cscfdc",
    "name": "Chandigarh SCs, BCs & Minorities Financial & Development Corporation Ltd. (CSCFDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Chandigarh",
    "district": "Chandigarh",
    "address": "3rd Floor, Additional Town Hall Building, Sector-17-C, Chandigarh-160 017.",
    "latitude": 30.7333,
    "longitude": 76.7794,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "chhatisgarh-state-antavasayee-sahkari-fin-dev-corpn-cgscfdc",
    "name": "Chhatisgarh State Antavasayee Sahkari Fin. & Dev.Corpn. (CGSCFDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Chhattisgarh",
    "district": "Naya Raipur",
    "address": "4th Floor, Business Complex, Chhattisgarh Housing Board Bhawan, Naya Raipur, Chhattisgarh - 492101.",
    "latitude": 21.167,
    "longitude": 81.7925,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "dadra-nagar-haveli-daman-diu-scs-sts-obcs-minorities-financial-development-corporation-dndsfdc",
    "name": "Dadra & Nagar Haveli, Daman & Diu SCs/STs/OBCs & Minorities Financial & Development Corporation (DNDSFDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Dadra & Nagar Haveli, Daman & Diu",
    "district": "Silvassa",
    "address": "Ground Floor, Right Wing, New Collectorate Building, Near Electricity Department, Opp. 66 KVA Sub-Station, 66 KVA Road, Silvassa \u2013 396 230.",
    "latitude": 20.2763,
    "longitude": 73.0083,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "delhi-sc-st-obc-minorities-handicapped-financial-development-corporation-dsfdc",
    "name": "Delhi SC/ST/OBC/Minorities & Handicapped Financial & Development Corporation (DSFDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Delhi",
    "district": "Delhi",
    "address": "Ambedkar Bhawan, Sector-16, (Opp. Sector-11), Rohini, Delhi \u2013 110 085.",
    "latitude": 28.6542,
    "longitude": 77.2373,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "the-managing-director-gujarat-scs-development-corporation-gscdc",
    "name": "The Managing Director, Gujarat SCs Development Corporation (GSCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Gujarat",
    "district": "Gandhinagar",
    "address": "Dr Jivraj Mehta Bhawan, Block \u2013 10, II Floor, Old Sachivalaya, Gandhinagar \u2013 382 010.",
    "latitude": 23.2156,
    "longitude": 72.6369,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "dr-ambedkar-antyodaya-vikas-nigam-s-c-daavn",
    "name": "Dr. Ambedkar Antyodaya Vikas Nigam (S.C.) (DAAVN)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Gujarat",
    "district": "Gandhinagar",
    "address": "Karmayogi Bhavan, Block No. 2, D-2 Wing, 4th Floor, Sector -10/B, Gandhinagar, Gujarat.",
    "latitude": 23.2216,
    "longitude": 72.6429,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "goa-state-scs-obcs-finance-and-development-corporation-ltd-gscobcdc",
    "name": "Goa State SCs & OBCs Finance and Development Corporation Ltd. (GSCOBCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Goa",
    "district": "Panaji",
    "address": "4th Floor, Patto Centre, Near K.T.C. Bus Stand, Panaji, Goa \u2013 403 001.",
    "latitude": 15.4909,
    "longitude": 73.8278,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "haryana-scs-fin-and-development-corporation-ltd-hscdc",
    "name": "Haryana SCs Fin. and Development Corporation Ltd. (HSCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Haryana",
    "district": "Chandigarh",
    "address": "SCO-2427-28, Sector 22-C, Chandigarh \u2013 160 022.",
    "latitude": 30.7393,
    "longitude": 76.7854,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "himachal-pradesh-scs-sts-development-corporation-hpscstdc",
    "name": "Himachal Pradesh SCs & STs Development Corporation (HPSCSTDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Himachal Pradesh",
    "district": "Solan",
    "address": "Kalyan Bhawan, Near Ambusha Resort, Solan \u2013 173212",
    "latitude": 30.9084,
    "longitude": 77.0999,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "jharkhand-state-scheduled-castes-cooperative-development-corporation-jscdc",
    "name": "Jharkhand State Scheduled Castes Cooperative Development Corporation (JSCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Jharkhand",
    "district": "Ranchi",
    "address": "Kalyan Complex, 3rd Floor, Balihar Road, Morabadi, Ranchi-834008.",
    "latitude": 23.3561,
    "longitude": 85.3216,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "j-k-scs-sts-obcs-dev-corpn-ltd-jkscstbcdc",
    "name": "J&K SCs, STs & OBCs Dev. Corpn. Ltd. (JKSCSTBCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Jammu & Kashmir",
    "district": "Srinagar/Jammu",
    "address": "Exchange Road, Near Red Cross Office, Srinagar \u2013 190 001 (Office: May to October) & 135-A, Last Morh, Gandhi Nagar, Jammu -180 004 (Office: November to April)",
    "latitude": 34.0837,
    "longitude": 74.7973,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "dr-b-r-ambedkar-development-corporation-ltd-dbradc",
    "name": "Dr B. R. Ambedkar Development Corporation Ltd. (DBRADC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Karnataka",
    "district": "Bengaluru",
    "address": "9th & 10th Floor, Visheshwariah Mini Tower, Dr Ambedkar Veedhi, Bengaluru \u2013 560 001.",
    "latitude": 12.9776,
    "longitude": 77.6006,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "kerala-state-development-corporation-for-scs-sts-ltd-ksdc",
    "name": "Kerala State Development Corporation for SCs & STs Ltd. (KSDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Kerala",
    "district": "Thrissur",
    "address": "Town Hall Road, Thrissur \u2013 680 020.",
    "latitude": 10.5276,
    "longitude": 76.2144,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "kerala-state-women-s-development-corporation-kswdc",
    "name": "Kerala State Women's Development Corporation (KSWDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Kerala",
    "district": "Thiruvananthapuram",
    "address": "1st Floor, Transport Bhavan, KSRTC Building, East Fort, Attakulangara-695023,",
    "latitude": 8.5241,
    "longitude": 76.9366,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "mp-state-cooperative-sc-finance-development-corporation-mpscfdc",
    "name": "MP State Cooperative SC Finance & Development Corporation (MPSCFDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Madhya Pradesh",
    "district": "Bhopal",
    "address": "Rajiv Gandhi Bhawan, 35, Shyamala Hills, Bhopal \u2013 462 011.",
    "latitude": 23.2599,
    "longitude": 77.4126,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "mahatma-phule-bcs-development-corporation-ltd-mpbcdc",
    "name": "Mahatma Phule BCs Development Corporation Ltd. (MPBCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Maharashtra",
    "district": "Mumbai",
    "address": "1-N, Supreme Shopping Centre, Gulmohar Cross Road No.9, J.V.P.D. Scheme, Juhu, Mumbai \u2013 400 049.",
    "latitude": 18.94,
    "longitude": 72.8527,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "sahityaratna-lokshahir-annabhau-sathe-development-corporation-ltd-slasdc",
    "name": "Sahityaratna Lokshahir Annabhau Sathe Development Corporation Ltd. (SLASDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Maharashtra",
    "district": "Mumbai",
    "address": "New Administration Building No.2, 3rd Floor, Ramkrushna Chemburkar Marg, Chembur (E), Mumbai \u2013 400 071.",
    "latitude": 18.946,
    "longitude": 72.8587,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "sant-rohidas-leather-industries-charmakar-development-corporation-lidcom",
    "name": "Sant Rohidas Leather Industries & Charmakar Development Corporation (LIDCOM)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Maharashtra",
    "district": "Mumbai",
    "address": "Bombay Life Building, 5th Floor, 45, Veer Nariman Road, Mumbai \u2013 400 001.",
    "latitude": 18.952,
    "longitude": 72.8647,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "manipur-tribal-development-corporation-ltd-mtdc",
    "name": "Manipur Tribal Development Corporation Ltd. (MTDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Manipur",
    "district": "Imphal",
    "address": "Lamphelpat, Imphal \u2013 795 004.",
    "latitude": 24.823,
    "longitude": 93.9428,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "manipur-scs-sts-co-operative-dev-bank-mstcb",
    "name": "Manipur SCs & STs Co-operative Dev. Bank (MSTCB)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Manipur",
    "district": "Imphal",
    "address": "Nambun Long, Stadium Road, Imphal East, MANIPUR-795001.",
    "latitude": 24.829,
    "longitude": 93.9488,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "meghalaya-cooperative-apex-bank-ltd-mcab",
    "name": "Meghalaya Cooperative Apex Bank Ltd. (MCAB)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Meghalaya",
    "district": "Shillong",
    "address": "M.G. Road, Kutchery, Shillong \u2013 793 001.",
    "latitude": 25.5848,
    "longitude": 91.8993,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "mizoram-urban-cooperative-development-bank-ltd-muco-bank",
    "name": "Mizoram Urban Cooperative Development Bank Ltd. (MUCO Bank)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Mizoram",
    "district": "Aizawl",
    "address": "Lawlsawmiliani Building (Top Floor), Zarkawt, Aizwal -796 001.",
    "latitude": 23.7331,
    "longitude": 92.7236,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "mizoram-khadi-village-industries-board-mkvib",
    "name": "Mizoram Khadi & Village Industries & Board (MKVIB)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Mizoram",
    "district": "Aizawl",
    "address": "\u201cZorun\u201d Zarkawt, Aizwal -796 007.",
    "latitude": 23.7391,
    "longitude": 92.7296,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "odisha-scs-sts-dev-finance-co-op-corpn-ltd-osfdc",
    "name": "Odisha SCs & STs Dev. Finance Co-op. Corpn. Ltd. (OSFDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Odisha",
    "district": "Bhubaneswar",
    "address": "Lewis Road, Bhubaneshwar \u2013 751 014.",
    "latitude": 20.3081,
    "longitude": 85.8365,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "puducherry-adi-dravidar-dev-corpn-ltd-padco",
    "name": "Puducherry Adi Dravidar Dev. Corpn. Ltd. (PADCO)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Puducherry",
    "district": "Puducherry",
    "address": "III Floor, Directorate of Adi Dravidar Welfare Department, Thattanchavady, Puducherry - 605 009",
    "latitude": 11.9476,
    "longitude": 79.8143,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "punjab-scheduled-castes-land-development-finance-corporation-pscldfc",
    "name": "Punjab Scheduled Castes Land Development & Finance Corporation (PSCLDFC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Punjab",
    "district": "Chandigarh",
    "address": "SCO No.101-102-103, Sector 17-C, Chandigarh \u2013 160 017.",
    "latitude": 30.7453,
    "longitude": 76.7914,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "rajasthan-scs-sts-fin-dev-co-op-corporation-ltd-rscdc",
    "name": "Rajasthan SCs & STs Fin. & Dev. Co-op. Corporation Ltd. (RSCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Rajasthan",
    "district": "Jaipur",
    "address": "III Floor, Central Block, Nehru Sahakar Bhawan, Bhawani Singh Marg, Jaipur\u2013302005.",
    "latitude": 26.9124,
    "longitude": 75.7873,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "sikkim-scheduled-castes-scheduled-tribes-backward-classes-development-corporation-sscstbcdc",
    "name": "Sikkim Scheduled Castes Scheduled Tribes & Backward Classes Development Corporation (SSCSTBCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Sikkim",
    "district": "Gangtok",
    "address": "Bhanupath, Gangtok, Sikkim \u2013 737 101.",
    "latitude": 27.3389,
    "longitude": 88.6065,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "tamil-nadu-adi-dravidar-housing-development-corporation-ltd-tahdco",
    "name": "Tamil Nadu Adi Dravidar Housing & Development Corporation Ltd. (TAHDCO)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Tamil Nadu",
    "district": "Chennai",
    "address": "No.31, Cenotaph Road, 2nd Lane, Teynamtet, Chennai -600 018.",
    "latitude": 13.0947,
    "longitude": 80.2827,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "tripura-scheduled-castes-co-op-devp-corpn-ltd-tscdc",
    "name": "Tripura Scheduled Castes Co-op. Devp. Corpn. Ltd. (TSCDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Tripura",
    "district": "Agartala",
    "address": "Krishna Nagar P.O. Lake Chomubani, Agartala \u2013 799 001",
    "latitude": 23.8375,
    "longitude": 91.2928,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "uttarakhand-bahu-udeshiya-vitta-evam-vikas-nigam-ubvevn",
    "name": "Uttarakhand Bahu-udeshiya Vitta Evam Vikas Nigam (UBVEVN)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Uttarakhand",
    "district": "Dehradun",
    "address": "Janjati Directorate, New Building, Bhagat Singh Clolony (Adhoiwala), Dehradun-248 001",
    "latitude": 30.3225,
    "longitude": 78.0382,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "up-sahkari-gram-vikas-bank-ltd",
    "name": "UP Sahkari Gram Vikas Bank Ltd.",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Uttar Pradesh",
    "district": "Lucknow",
    "address": "10, Mall Avenue, Lucknow, Uttar Pradesh-226001.",
    "latitude": 26.8587,
    "longitude": 80.9582,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "up-scheduled-castes-finance-dev-corpn-ltd-upscfdc",
    "name": "UP Scheduled Castes Finance & Dev. Corpn. Ltd. (UPSCFDC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "Uttar Pradesh",
    "district": "Lucknow",
    "address": "B-912, Sector-C, Mahanagar, Lucknow \u2013 226 006.",
    "latitude": 26.8647,
    "longitude": 80.9642,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "west-bengal-scs-sts-obc-development-finance-corporation-wbscstobcdfc",
    "name": "West Bengal SCs, STs & OBC Development & Finance Corporation (WBSCSTOBCDFC)",
    "type": "State Channelizing Agencies (SCAs)",
    "shortType": "SCA",
    "state": "West Bengal",
    "district": "Kolkata",
    "address": "CF 217/A/1 Salt Lake Sector \u2013I, (Mangolic Building), Kolkata \u2013 700 064.",
    "latitude": 22.5846,
    "longitude": 88.3759,
    "supportedSchemes": [
      "mfs",
      "term-loan",
      "aajeevika",
      "udyam-nidhi",
      "els"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "au-small-finance-bank",
    "name": "AU Small Finance Bank",
    "type": "Small Finance Banks (SFBs)",
    "shortType": "SFB",
    "state": "India",
    "district": "Head Office",
    "address": "AU Small Finance Bank, India",
    "latitude": 20.5937,
    "longitude": 78.9629,
    "supportedSchemes": [
      "udyam-nidhi",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  },
  {
    "id": "ujjivan-small-finance-bank",
    "name": "Ujjivan Small Finance Bank",
    "type": "Small Finance Banks (SFBs)",
    "shortType": "SFB",
    "state": "India",
    "district": "Head Office",
    "address": "Ujjivan Small Finance Bank, India",
    "latitude": 20.5997,
    "longitude": 78.9689,
    "supportedSchemes": [
      "udyam-nidhi",
      "mfs"
    ],
    "contactPhone": "1800-11-2004 / 011-22000000",
    "workingHours": "Mon - Sat (10:00 AM - 5:00 PM)",
    "website": "https://nsfdc.nic.in",
    "verificationStatus": "Verified Official Partner",
    "lastVerifiedDate": "2026-09-24",
    "isDemoData": false
  }
];
