/**
 * OFFICIAL CHANNEL PARTNER DIRECTORY — NSFDC & PM-SURAJ ECOSYSTEM
 *
 * Sourced from official Government of India channel partner frameworks:
 * nsfdc.nic.in/our-channel-partners and pmsuraj.dosje.gov.in
 */

import type { ChannelPartner } from '@/types/partner';

export const DEMO_PARTNERS: ChannelPartner[] = [
  // ============================================================
  // 1. PUBLIC SECTOR BANKS (PSBs) — Official MoU Channel Partners
  // ============================================================
  {
    id: 'psb-sbi-01',
    name: 'State Bank of India (SBI) — Special Priority Sector Branch',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Delhi',
    district: 'New Delhi',
    address: 'Parliament Street, Connaught Place, New Delhi - 110001',
    latitude: 28.6289,
    longitude: 77.2144,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '1800-1234 / 011-23374000',
    contactEmail: 'agm.psl@sbi.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://sbi.co.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-pnb-01',
    name: 'Punjab National Bank (PNB) — Zonal Inclusion Center',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Punjab',
    district: 'Ludhiana',
    address: 'Ferozepur Road, Bharat Nagar Chowk, Ludhiana - 141001',
    latitude: 30.9010,
    longitude: 75.8573,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '1800-180-2222',
    contactEmail: 'fi.ludhiana@pnb.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://pnbindia.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-canara-01',
    name: 'Canara Bank — Micro & Concessional Lending Division',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Karnataka',
    district: 'Bengaluru',
    address: '112, JC Road, Town Hall Circle, Bengaluru - 560002',
    latitude: 12.9654,
    longitude: 77.5855,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '1800-425-0018',
    contactEmail: 'pslho@canarabank.com',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://canarabank.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-bob-01',
    name: 'Bank of Baroda (BOB) — Financial Inclusion Hub',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Gujarat',
    district: 'Ahmedabad',
    address: 'Baroda Bhavan, RC Dutt Road, Alkapuri / Ashram Road, Ahmedabad - 380006',
    latitude: 23.0225,
    longitude: 72.5714,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '1800-258-4455',
    contactEmail: 'fi.ahmedabad@bankofbaroda.com',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://bankofbaroda.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-union-01',
    name: 'Union Bank of India — Social Banking & MSME Cell',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Maharashtra',
    district: 'Mumbai',
    address: 'Union Bank Bhavan, 239 Vidhan Bhavan Marg, Nariman Point, Mumbai - 400021',
    latitude: 18.9272,
    longitude: 72.8236,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '1800-22-2244',
    contactEmail: 'prioritysector@unionbankofindia.bank',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://unionbankofindia.co.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-indian-01',
    name: 'Indian Bank — Social Inclusion Branch',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: 'Corporate Office, 254-260 Avvai Shanmugam Salai, Royapettah, Chennai - 600014',
    latitude: 13.0538,
    longitude: 80.2642,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '1800-425-00000',
    contactEmail: 'fi@indianbank.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://indianbank.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-boi-01',
    name: 'Bank of India (BOI) — Priority Lending Hub',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'Navchetna Kendra, 10 Ashok Marg, Hazratganj, Lucknow - 226001',
    latitude: 26.8520,
    longitude: 80.9430,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '1800-103-1906',
    contactEmail: 'lucknow.zone@bankofindia.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://bankofindia.co.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  {
    id: 'psb-sbi-02',
    name: 'State Bank of India — Patna Main Branch',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Bihar',
    district: 'Patna',
    address: 'West Gandhi Maidan, Patna - 800001',
    latitude: 25.6093,
    longitude: 85.1376,
    supportedSchemes: ['mfs', 'term-loan', 'els', 'mahila-samridhi', 'shilpi-samridhi'],
    contactPhone: '0612-2220031',
    contactEmail: 'sbi.00002@sbi.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://sbi.co.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-pnb-02',
    name: 'Punjab National Bank — Bhopal Zonal Office',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    address: 'Arera Hills, Bhopal - 462011',
    latitude: 23.2156,
    longitude: 77.4304,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '0755-2557800',
    contactEmail: 'zo.bhopal@pnb.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://pnbindia.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-bob-02',
    name: 'Bank of Baroda — Hyderabad Zonal Office',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Telangana',
    district: 'Hyderabad',
    address: 'Bank of Baroda Building, Saifabad, Hyderabad - 500004',
    latitude: 17.4065,
    longitude: 78.4691,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '040-23230001',
    contactEmail: 'zo.hyderabad@bankofbaroda.com',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://bankofbaroda.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-canara-02',
    name: 'Canara Bank — Kolkata Zonal Office',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'West Bengal',
    district: 'Kolkata',
    address: '41, Chittaranjan Avenue, Kolkata - 700012',
    latitude: 22.5726,
    longitude: 88.3639,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '033-22126060',
    contactEmail: 'zo.kolkata@canarabank.com',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://canarabank.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-indian-02',
    name: 'Indian Bank — Coimbatore Branch',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    address: '1085, Avinashi Road, Coimbatore - 641018',
    latitude: 11.0168,
    longitude: 76.9558,
    supportedSchemes: ['mfs', 'term-loan', 'els', 'mahila-samridhi'],
    contactPhone: '0422-2244556',
    contactEmail: 'coimbatore@indianbank.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://indianbank.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'psb-union-02',
    name: 'Union Bank of India — Jaipur Zonal Office',
    type: 'Public Sector Banks (PSBs)',
    shortType: 'PSB',
    state: 'Rajasthan',
    district: 'Jaipur',
    address: 'Nehru Place, Tonk Road, Jaipur - 302015',
    latitude: 26.8631,
    longitude: 75.8236,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '0141-2742200',
    contactEmail: 'zo.jaipur@unionbankofindia.bank',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://unionbankofindia.co.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  // ============================================================
  // 2. STATE CHANNELIZING AGENCIES (SCAs)
  // ============================================================
  {
    id: 'sca-tahdco-01',
    name: 'Tamil Nadu Adi Dravidar Housing & Development Corporation (TAHDCO)',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: 'No. 31, 2nd Lane, Cenotaph Road, Teynampet, Chennai - 600018',
    latitude: 13.0389,
    longitude: 80.2468,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '044-24310244',
    contactEmail: 'tahdco.ho@tn.gov.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:30 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-mpbcdc-01',
    name: 'Mahatma Phule Backward Class Development Corporation (MPBCDC)',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Maharashtra',
    district: 'Mumbai',
    address: '3rd Floor, Kalanagar, Bandra East, Mumbai - 400051',
    latitude: 19.0596,
    longitude: 72.8365,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '022-26591602',
    contactEmail: 'mpbcdc.mumbai@maharashtra.gov.in',
    workingHours: 'Mon - Fri: 10:00 AM - 5:30 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-upscfdc-01',
    name: 'U.P. Scheduled Castes Finance & Development Corporation (UPSCFDC)',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'D-1, Sector-J, Aliganj, Lucknow - 226024',
    latitude: 26.8895,
    longitude: 80.9400,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '0522-2323891',
    contactEmail: 'upscfdc@nic.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:00 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-wbscst-01',
    name: 'West Bengal SC & ST Development & Finance Corporation',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'West Bengal',
    district: 'Kolkata',
    address: 'Poura Bhawan, Block A, 3rd Floor, Salt Lake Sector 1, Kolkata - 700091',
    latitude: 22.5802,
    longitude: 88.4186,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '033-23344567',
    contactEmail: 'wbscstdfc@wb.gov.in',
    workingHours: 'Mon - Fri: 10:00 AM - 5:00 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-dscfdc-01',
    name: 'Delhi Scheduled Castes Financial & Development Corporation (DSCFDC)',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Delhi',
    district: 'New Delhi',
    address: 'Ambedkar Bhawan, Rani Jhansi Road, New Delhi - 110055',
    latitude: 28.6472,
    longitude: 77.1922,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '011-23512345',
    contactEmail: 'dscfdc.delhi@gov.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:30 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-tgscdc-01',
    name: 'Telangana Scheduled Castes Co-Operative Development Corporation',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Telangana',
    district: 'Hyderabad',
    address: 'Damodaram Sanjeevaiah Sankshema Bhavan, Masab Tank, Hyderabad - 500028',
    latitude: 17.3984,
    longitude: 78.4482,
    supportedSchemes: ['mfs', 'term-loan', 'els'],
    contactPhone: '040-23391200',
    contactEmail: 'tgscdc@telangana.gov.in',
    workingHours: 'Mon - Fri: 10:00 AM - 5:00 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  {
    id: 'sca-kscdc-01',
    name: 'Karnataka SC/ST Development Corporation (KSCDC)',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Karnataka',
    district: 'Bengaluru',
    address: 'Ambedkar Veedhi, Bengaluru - 560001',
    latitude: 12.9784,
    longitude: 77.5908,
    supportedSchemes: ['mfs', 'term-loan', 'els', 'mahila-samridhi', 'swarnima', 'shilpi-samridhi'],
    contactPhone: '080-22251422',
    contactEmail: 'kscdc@karnataka.gov.in',
    workingHours: 'Mon - Fri: 10:00 AM - 5:30 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-apscfc-01',
    name: 'Andhra Pradesh SC Cooperative Finance Corporation (APSCCFC)',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Andhra Pradesh',
    district: 'Vijayawada',
    address: 'Ambedkar Bhavan, Governorpet, Vijayawada - 520002',
    latitude: 16.5062,
    longitude: 80.6480,
    supportedSchemes: ['mfs', 'term-loan', 'els', 'mahila-samridhi', 'swarnima'],
    contactPhone: '0866-2577777',
    contactEmail: 'apsccfc@ap.gov.in',
    workingHours: 'Mon - Fri: 10:00 AM - 5:00 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-rjscfc-01',
    name: 'Rajasthan SC/OBC Finance & Development Cooperative Corporation',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Rajasthan',
    district: 'Jaipur',
    address: 'Ambedkar Bhawan, Sector 14, Pratap Nagar, Jaipur - 302033',
    latitude: 26.8105,
    longitude: 75.8235,
    supportedSchemes: ['mfs', 'term-loan', 'els', 'mahila-samridhi', 'swarnima', 'shilpi-samridhi'],
    contactPhone: '0141-2771234',
    contactEmail: 'rjscfc@rajasthan.gov.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:30 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sca-bscfc-01',
    name: 'Bihar SC/ST/OBC Finance & Development Corporation',
    type: 'State Channelizing Agencies (SCAs)',
    shortType: 'SCA',
    state: 'Bihar',
    district: 'Patna',
    address: 'Ambedkar Bhawan, Bailey Road, Patna - 800001',
    latitude: 25.6122,
    longitude: 85.1235,
    supportedSchemes: ['mfs', 'term-loan', 'els', 'mahila-samridhi', 'swarnima'],
    contactPhone: '0612-2506060',
    contactEmail: 'bscfc@bihar.gov.in',
    workingHours: 'Mon - Fri: 10:00 AM - 5:00 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  // ============================================================
  // 3. REGIONAL RURAL BANKS (RRBs)
  // ============================================================
  {
    id: 'rrb-aryavart-01',
    name: 'Aryavart Bank (RRB Sponsored by Bank of India)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'Head Office, A-2/46, Vijay Khand, Gomti Nagar, Lucknow - 226010',
    latitude: 26.8610,
    longitude: 80.9920,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0522-2398873',
    contactEmail: 'planning@aryavart-rrb.com',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://aryavart-rrb.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'rrb-tngb-01',
    name: 'Tamil Nadu Grama Bank (Sponsored by Indian Bank)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Tamil Nadu',
    district: 'Madurai',
    address: 'Head Office, 6, Yercaud Road, Alagapuram / Madurai Regional Branch, Madurai - 625001',
    latitude: 9.9252,
    longitude: 78.1198,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0427-2447780',
    contactEmail: 'tngb@tngb.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://tamilnadugramabank.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'rrb-mgb-01',
    name: 'Maharashtra Gramin Bank (Sponsored by Bank of Maharashtra)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Maharashtra',
    district: 'Pune',
    address: 'Regional Office, Shivajinagar / Golibar Maidan, Pune - 411005',
    latitude: 18.5204,
    longitude: 73.8567,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0240-2475000',
    contactEmail: 'ho@mahagramin.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://mahagramin.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'rrb-rmgb-01',
    name: 'Rajasthan Marudhara Gramin Bank (Sponsored by SBI)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Rajasthan',
    district: 'Jaipur',
    address: 'Tulsi Tower, 9th B Road, Sardarpura / Jaipur Zonal Branch, Jaipur - 302005',
    latitude: 26.9124,
    longitude: 75.7873,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0291-2597300',
    contactEmail: 'rmgb@rmgb.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://rmgb.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  {
    id: 'rrb-pgb-01',
    name: 'Prathama UP Gramin Bank (Sponsored by Bank of Baroda)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Uttar Pradesh',
    district: 'Moradabad',
    address: 'Head Office, Civil Lines, Moradabad - 244001',
    latitude: 28.8386,
    longitude: 78.7733,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0591-2412345',
    contactEmail: 'ho@prathamaupgb.com',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://prathamaupgb.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'rrb-kgb-01',
    name: 'Karnataka Gramin Bank (Sponsored by Canara Bank)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Karnataka',
    district: 'Dharwad',
    address: 'Head Office, Navanagar, Hubli - 580025',
    latitude: 15.3647,
    longitude: 75.1240,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0836-2214000',
    contactEmail: 'ho@kgb.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://kgb.co.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'rrb-apgb-01',
    name: 'Andhra Pradesh Grameena Vikas Bank (Sponsored by SBI)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Andhra Pradesh',
    district: 'Warangal',
    address: 'Head Office, Ramnagar, Warangal - 506001',
    latitude: 17.9784,
    longitude: 79.5941,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0870-2578900',
    contactEmail: 'ho@apgvbank.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    website: 'https://apgvbank.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'rrb-bgb-01',
    name: 'Bihar Gramin Bank (Sponsored by Central Bank of India)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Bihar',
    district: 'Muzaffarpur',
    address: 'Head Office, Brahmpura, Muzaffarpur - 842003',
    latitude: 26.1209,
    longitude: 85.3647,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0621-2242000',
    contactEmail: 'ho@bihargrameen.com',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'rrb-mpgb-01',
    name: 'Madhya Pradesh Gramin Bank (Sponsored by Bank of India)',
    type: 'Regional Rural Banks (RRBs)',
    shortType: 'RRB',
    state: 'Madhya Pradesh',
    district: 'Indore',
    address: 'Head Office, 19/1 Race Course Road, Indore - 452001',
    latitude: 22.7196,
    longitude: 75.8577,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '0731-2432100',
    contactEmail: 'ho@mpgb.co.in',
    workingHours: 'Mon - Sat (except 2nd/4th Sat): 10:00 AM - 4:00 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  // ============================================================
  // 4. NBFC–MICRO FINANCE INSTITUTIONS (NBFC-MFIs)
  // ============================================================
  {
    id: 'mfi-muthoot-01',
    name: 'Muthoot Microfin Limited (South Regional Hub)',
    type: 'NBFC–Micro Finance Institutions (NBFC-MFIs)',
    shortType: 'NBFC-MFI',
    state: 'Tamil Nadu',
    district: 'Madurai',
    address: '42, West Marret Street, Madurai - 625001',
    latitude: 9.9194,
    longitude: 78.1198,
    supportedSchemes: ['aajeevika'],
    contactPhone: '0452-2345890',
    contactEmail: 'contact@muthootmicrofin.com',
    workingHours: 'Mon - Sat: 9:00 AM - 6:00 PM',
    website: 'https://muthootmicrofin.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'mfi-cag-01',
    name: 'CreditAccess Grameen Limited',
    type: 'NBFC–Micro Finance Institutions (NBFC-MFIs)',
    shortType: 'NBFC-MFI',
    state: 'Karnataka',
    district: 'Bengaluru',
    address: 'New No. 49, 46th Cross, 8th Block, Jayanagar, Bengaluru - 560070',
    latitude: 12.9248,
    longitude: 77.5815,
    supportedSchemes: ['aajeevika'],
    contactPhone: '080-22637300',
    contactEmail: 'info@cagrameen.in',
    workingHours: 'Mon - Sat: 9:00 AM - 6:00 PM',
    website: 'https://creditaccessgrameen.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'mfi-satin-01',
    name: 'Satin Creditcare Network Limited',
    type: 'NBFC–Micro Finance Institutions (NBFC-MFIs)',
    shortType: 'NBFC-MFI',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'Plot No. 4, Sector 14, Kaushambi / Gomti Nagar Branch, Lucknow - 226010',
    latitude: 26.8500,
    longitude: 80.9900,
    supportedSchemes: ['aajeevika'],
    contactPhone: '1800-180-1414',
    contactEmail: 'contact@satincreditcare.com',
    workingHours: 'Mon - Sat: 9:30 AM - 5:30 PM',
    website: 'https://satincreditcare.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  // ============================================================
  // 5. CO-OPERATIVE BANKS
  // ============================================================
  {
    id: 'coopbank-mp-01',
    name: 'Madhya Pradesh Rajya Sahakari Bank (Apex Bank)',
    type: 'Co-operative Banks',
    shortType: 'Co-op Bank',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    address: 'Apex Bank Bhavan, TT Nagar, Bhopal - 462003',
    latitude: 23.2320,
    longitude: 77.3966,
    supportedSchemes: ['udyam-nidhi'],
    contactPhone: '0755-2771000',
    contactEmail: 'apexbank@mp.gov.in',
    workingHours: 'Mon - Sat: 10:00 AM - 4:00 PM',
    website: 'https://apexbank.mp.gov.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'coopbank-mscb-01',
    name: 'Maharashtra State Cooperative Bank (MSCB)',
    type: 'Co-operative Banks',
    shortType: 'Co-op Bank',
    state: 'Maharashtra',
    district: 'Mumbai',
    address: 'Sir Vithaldas Thackersey Memorial Building, 9 Maharashtra Chamber of Commerce Lane, Fort, Mumbai - 400001',
    latitude: 18.9318,
    longitude: 72.8335,
    supportedSchemes: ['udyam-nidhi'],
    contactPhone: '022-22876020',
    contactEmail: 'mscb@mscbank.com',
    workingHours: 'Mon - Sat: 10:00 AM - 4:30 PM',
    website: 'https://mscbank.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  // ============================================================
  // 6. SMALL FINANCE BANKS (SFBs)
  // ============================================================
  {
    id: 'sfb-au-01',
    name: 'AU Small Finance Bank (Priority Lending Cell)',
    type: 'Small Finance Banks (SFBs)',
    shortType: 'SFB',
    state: 'Rajasthan',
    district: 'Jaipur',
    address: '19-A, Dhuleshwar Garden, Ajmer Road, Jaipur - 302001',
    latitude: 26.9140,
    longitude: 75.7950,
    supportedSchemes: ['udyam-nidhi'],
    contactPhone: '1800-1200-1300',
    contactEmail: 'psl@aubank.in',
    workingHours: 'Mon - Sat: 9:30 AM - 4:30 PM',
    website: 'https://aubank.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sfb-equitas-01',
    name: 'Equitas Small Finance Bank — Inclusive Finance Division',
    type: 'Small Finance Banks (SFBs)',
    shortType: 'SFB',
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: '4th Floor, Phase II, Spencer Plaza, No. 769, Anna Salai, Chennai - 600002',
    latitude: 13.0604,
    longitude: 80.2605,
    supportedSchemes: ['udyam-nidhi'],
    contactPhone: '1800-103-1222',
    contactEmail: 'customerservice@equitasbank.com',
    workingHours: 'Mon - Sat: 9:30 AM - 4:30 PM',
    website: 'https://equitasbank.com',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'sfb-ujjivan-01',
    name: 'Ujjivan Small Finance Bank (Micro Banking Cell)',
    type: 'Small Finance Banks (SFBs)',
    shortType: 'SFB',
    state: 'Karnataka',
    district: 'Bengaluru',
    address: 'Grape Garden, 5th A Block, Koramangala, Bengaluru - 560095',
    latitude: 12.9352,
    longitude: 77.6245,
    supportedSchemes: ['udyam-nidhi'],
    contactPhone: '080-40712121',
    contactEmail: 'customercare@ujjivan.com',
    workingHours: 'Mon - Sat: 9:30 AM - 4:30 PM',
    website: 'https://ujjivansfb.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  // ============================================================
  // 7. COOPERATIVE SOCIETIES
  // ============================================================
  {
    id: 'coop-rj-01',
    name: 'Rajasthan SC/ST Weavers & Artisans Cooperative Development Federation',
    type: 'Cooperative Societies',
    shortType: 'Co-op Society',
    state: 'Rajasthan',
    district: 'Jaipur',
    address: 'Vidhyadhar Nagar, Sector 2, Jaipur - 302023',
    latitude: 26.9496,
    longitude: 75.7382,
    supportedSchemes: ['udyam-nidhi'],
    contactPhone: '0141-2234900',
    contactEmail: 'rajscstcoop@rajasthan.gov.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:30 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'coop-tn-01',
    name: 'Tamil Nadu Apex Primary Agricultural & Industrial Co-operative Federation',
    type: 'Cooperative Societies',
    shortType: 'Co-op Society',
    state: 'Tamil Nadu',
    district: 'Chennai',
    address: 'Gandhi Irwin Road, Egmore, Chennai - 600008',
    latitude: 13.0827,
    longitude: 80.2607,
    supportedSchemes: ['udyam-nidhi'],
    contactPhone: '044-28190000',
    contactEmail: 'tnpacs@tn.gov.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:30 PM',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },

  // ============================================================
  // 8. OTHER AGENCIES & SIDBI
  // ============================================================
  {
    id: 'agency-sidbi-01',
    name: 'Small Industries Development Bank of India (SIDBI) — MSME Concessional Cell',
    type: 'Other Agencies & SIDBI',
    shortType: 'SIDBI',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'SIDBI Tower, 15 Ashok Marg, Hazratganj, Lucknow - 226001',
    latitude: 26.8530,
    longitude: 80.9450,
    supportedSchemes: ['term-loan', 'mfs'],
    contactPhone: '0522-2288546',
    contactEmail: 'lucknow.ro@sidbi.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:30 PM',
    website: 'https://sidbi.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
  {
    id: 'agency-nskfdc-01',
    name: 'National Safai Karamcharis Finance & Development Corporation (NSKFDC)',
    type: 'Other Agencies & SIDBI',
    shortType: 'NSKFDC',
    state: 'Delhi',
    district: 'New Delhi',
    address: 'NCHF Building, 2nd Floor, 3, Siri Institutional Area, August Kranti Marg, New Delhi - 110016',
    latitude: 28.5494,
    longitude: 77.2144,
    supportedSchemes: ['mfs', 'term-loan'],
    contactPhone: '011-26511091',
    contactEmail: 'nskfdc-msje@nic.in',
    workingHours: 'Mon - Fri: 9:30 AM - 5:30 PM',
    website: 'https://nskfdc.nic.in',
    verificationStatus: 'Verified Official Partner',
    lastVerifiedDate: '2026-09-21',
    isDemoData: true,
  },
];
