/**
 * VERIFIED SCHEME DATA — NSFDC Concessional Credit Schemes
 *
 * Source: nsfdc.nic.in/scheme
 * Last verified: 2026-09-21
 *
 * ⚠️  Every figure here must match the official NSFDC website.
 *     Do NOT invent, round, or approximate any number.
 *     If a figure cannot be verified, use null and display the
 *     "Information currently unavailable" disclaimer.
 */

import type { Scheme } from '@/types/scheme';

export const VERIFIED_SCHEMES: Scheme[] = [
  {
    id: 'mfs',
    name: 'Micro Finance Scheme',
    shortName: 'MFS',
    category: 'Micro Enterprise',
    purpose: 'Small/micro business activities with project cost up to ₹1.40 lakh',
    description:
      'Provides prompt, need-based credit for small and micro income-generating business activities for members of Scheduled Castes living below Double the Poverty Line. Covers activities such as petty trade, small shops, tailoring, repair services, and other self-employment ventures. Loans are disbursed through State Channelizing Agencies (SCAs), Public Sector Banks, and Regional Rural Banks.',
    eligibility: [
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000 (Double the Poverty Line)',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Project Cost',
        description: 'Total project cost must be up to ₹1,40,000',
        field: 'estimatedProjectCost',
        value: 140000,
      },
    ],
    financialDetails: {
      maxLoanAmount: 125000,
      maxProjectCost: 140000,
      interestRate: 6.5,
      repaymentPeriod: '3 years, quarterly instalments',
      repaymentPeriodMonths: 36,
      moratorium: '3 months',
      moratoriumMonths: 3,
      coverage: '90% of project cost',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Project report / business plan',
      'Bank account details',
      'Passport-size photographs',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: [
      'State Channelizing Agencies (SCAs)',
      'Public Sector Banks (PSBs)',
      'Regional Rural Banks (RRBs)',
    ],
  },
  {
    id: 'term-loan',
    name: 'Term Loan Scheme',
    shortName: 'Term Loan',
    category: 'Enterprise Finance',
    purpose: 'Larger income-generating activities with project cost from ₹1.40 lakh to ₹50 lakh',
    description:
      'Financial assistance for income-generating activities where the project cost exceeds the Micro Finance Scheme ceiling. Covers manufacturing, services, agriculture, transport, and allied activities. Suitable for setting up workshops, buying machinery, commercial vehicles, and other capital-intensive ventures. Loans are disbursed through State Channelizing Agencies (SCAs), Public Sector Banks, RRBs, and SIDBI.',
    eligibility: [
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Project Cost',
        description: 'Total project cost must be between ₹1,40,000 and ₹50,00,000',
        field: 'estimatedProjectCost',
        value: '140000-5000000',
      },
    ],
    financialDetails: {
      maxLoanAmount: 4500000,
      maxProjectCost: 5000000,
      interestRate: 8,
      repaymentPeriod: '7 years, quarterly instalments',
      repaymentPeriodMonths: 84,
      moratorium: '6 months (12 months for plantation/construction projects)',
      moratoriumMonths: 6,
      moratoriumNote: '12 months for plantation/construction projects',
      coverage: '90% of project cost',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Detailed project report',
      'Quotations for machinery/equipment (if applicable)',
      'Bank account details',
      'Passport-size photographs',
      'Collateral/security documents (as per SCA requirements)',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: [
      'State Channelizing Agencies (SCAs)',
      'Public Sector Banks (PSBs)',
      'Regional Rural Banks (RRBs)',
      'Other Agencies & SIDBI',
    ],
  },
  {
    id: 'aajeevika',
    name: 'Aajeevika Micro-Finance Yojana',
    shortName: 'Aajeevika MFY',
    category: 'Micro Enterprise',
    purpose: 'Small/micro business activities via NBFC-MFIs with project cost up to ₹1.40 lakh',
    description:
      'Micro-finance scheme channeled exclusively through NBFC-MFIs (Non-Banking Financial Company – Micro Finance Institutions) for small and micro income-generating activities. Designed to reach SC beneficiaries in areas where traditional SCA coverage is limited, particularly in rural and semi-urban regions. Covers petty trade, animal husbandry, handicrafts, and other micro-enterprises.',
    eligibility: [
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Project Cost',
        description: 'Total project cost must be up to ₹1,40,000',
        field: 'estimatedProjectCost',
        value: 140000,
      },
    ],
    financialDetails: {
      maxLoanAmount: 125000,
      maxProjectCost: 140000,
      interestRate: 15,
      repaymentPeriod: '3 years, quarterly instalments',
      repaymentPeriodMonths: 36,
      moratorium: '3 months',
      moratoriumMonths: 3,
      coverage: '90% of project cost',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Business activity details',
      'Bank account details',
      'Passport-size photographs',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: ['NBFC–Micro Finance Institutions (NBFC-MFIs)'],
  },
  {
    id: 'udyam-nidhi',
    name: 'Udyam Nidhi Yojana',
    shortName: 'Udyam Nidhi',
    category: 'Enterprise Finance',
    purpose: 'Business activities via Cooperative Societies/Banks/SFBs with project cost up to ₹5 lakh',
    description:
      'Enterprise finance scheme channeled through Cooperative Societies, Cooperative Banks, and Small Finance Banks (SFBs). Provides credit for income-generating activities including small manufacturing, service enterprises, and trade. Offers a higher project cost ceiling than micro-finance schemes and is accessible through cooperative banking channels across India.',
    eligibility: [
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Project Cost',
        description: 'Total project cost must be up to ₹5,00,000',
        field: 'estimatedProjectCost',
        value: 500000,
      },
    ],
    financialDetails: {
      maxLoanAmount: 450000,
      maxProjectCost: 500000,
      interestRate: 13,
      interestRateAlt: 15,
      interestRateNote: '13% p.a. via Cooperative Societies/Banks; 15% p.a. via Small Finance Banks',
      repaymentPeriod: 'Up to 5 years',
      repaymentPeriodMonths: 60,
      moratorium: '3 months',
      moratoriumMonths: 3,
      coverage: '90% of project cost',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Business activity details / project report',
      'Bank account details',
      'Passport-size photographs',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: [
      'Cooperative Societies',
      'Co-operative Banks',
      'Small Finance Banks (SFBs)',
    ],
  },
  {
    id: 'els',
    name: 'Educational Loan Scheme',
    shortName: 'ELS',
    category: 'Education',
    purpose: 'Higher education financing for professional and technical courses in India and abroad',
    description:
      'Educational loan for SC students pursuing professional and technical education at recognized institutions in India and abroad. Covers tuition fees, hostel charges, examination fees, purchase of books/equipment, and other course-related expenses. Loan amount is up to 90% of the course fee or ₹40 lakh, whichever is less. Repayment begins after course completion with a generous moratorium period.',
    eligibility: [
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Admission',
        description: 'Must have secured admission in a recognized professional/technical course at a recognized institution',
        field: 'educationLevel',
        value: 'higher_education',
      },
    ],
    financialDetails: {
      maxLoanAmount: 4000000,  // ₹40 lakh — unified cap for India and abroad
      maxProjectCost: 4000000,
      interestRate: 6.5,
      interestRateNote: 'Up to ₹40 lakh or 90% of course fee, whichever is less',
      repaymentPeriod: '10 years repayment period after moratorium',
      repaymentPeriodMonths: 120,
      moratorium: 'Course period + 1 year (or 6 months after getting employment)',
      moratoriumMonths: undefined,
      moratoriumNote: 'Moratorium is course duration plus one year, or six months after course completion/employment, whichever is earlier',
      coverage: '90% of course fee',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Admission letter from recognized institution',
      'Fee structure / prospectus of the course',
      'Academic records / marksheets of previous qualifying examination',
      'Bank account details',
      'Passport-size photographs',
      'Co-applicant (parent/guardian) identity and address proof',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: [
      'State Channelizing Agencies (SCAs)',
      'Public Sector Banks (PSBs)',
    ],
  },
  {
    id: 'mahila-samridhi',
    name: 'Mahila Samridhi Yojana',
    shortName: 'MSY',
    category: 'Women Empowerment',
    purpose: 'Income-generating activities exclusively for SC women with project cost up to ₹1.40 lakh',
    description:
      'Dedicated micro-finance scheme for Scheduled Caste women to support income-generating activities. Provides concessional credit at a lower interest rate than the general MFS to encourage women entrepreneurship. Covers activities such as tailoring, beauty parlour, food processing, handicrafts, animal husbandry, and other self-employment ventures. Channeled through SCAs.',
    eligibility: [
      {
        criterion: 'Gender',
        description: 'Applicant must be a woman',
        field: 'gender',
        value: 'female',
      },
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Project Cost',
        description: 'Total project cost must be up to ₹1,40,000',
        field: 'estimatedProjectCost',
        value: 140000,
      },
    ],
    financialDetails: {
      maxLoanAmount: 125000,
      maxProjectCost: 140000,
      interestRate: 5,
      interestRateNote: 'Concessional rate of 5% p.a. exclusively for SC women beneficiaries',
      repaymentPeriod: '3 years, quarterly instalments',
      repaymentPeriodMonths: 36,
      moratorium: '3 months',
      moratoriumMonths: 3,
      coverage: '90% of project cost',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Project report / business plan',
      'Bank account details',
      'Passport-size photographs',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: ['State Channelizing Agencies (SCAs)'],
  },
  {
    id: 'swarnima',
    name: 'Swarnima Scheme',
    shortName: 'Swarnima',
    category: 'Women Empowerment',
    purpose: 'Self-employment for SC women — individual loan up to ₹1 lakh without collateral',
    description:
      'Individual loan scheme for SC women for self-employment and income-generating activities. A key feature is that no collateral or guarantor is required, making it accessible to women who may not have assets to pledge. Covers activities such as small shops, food stalls, stitching, embroidery, and other micro-enterprises. Channeled through SCAs.',
    eligibility: [
      {
        criterion: 'Gender',
        description: 'Applicant must be a woman',
        field: 'gender',
        value: 'female',
      },
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Collateral',
        description: 'No collateral or guarantor required',
        field: 'collateral',
        value: 'none_required',
      },
    ],
    financialDetails: {
      maxLoanAmount: 100000,
      maxProjectCost: 100000,
      interestRate: 5,
      interestRateNote: '5% p.a. — no collateral or guarantor required',
      repaymentPeriod: '5 years',
      repaymentPeriodMonths: 60,
      moratorium: '3 months',
      moratoriumMonths: 3,
      coverage: '100% of loan amount (no margin money required)',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Business activity details',
      'Bank account details',
      'Passport-size photographs',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: ['State Channelizing Agencies (SCAs)'],
  },
  {
    id: 'shilpi-samridhi',
    name: 'Shilpi Samridhi Yojana',
    shortName: 'Shilpi Samridhi',
    category: 'Artisan & Craft',
    purpose: 'Credit support for SC artisans and craftspersons for tools, equipment, and working capital',
    description:
      'Dedicated credit scheme for Scheduled Caste artisans, craftspersons, and traditional workers to purchase tools, equipment, raw materials, and working capital. Covers weavers, potters, cobblers, carpenters, blacksmiths, and other traditional artisans. Aims to modernize traditional crafts and improve the income of SC artisan communities.',
    eligibility: [
      {
        criterion: 'Caste Category',
        description: 'Must belong to Scheduled Caste (SC) community with a valid caste certificate issued by competent authority',
        field: 'category',
        value: 'SC',
      },
      {
        criterion: 'Occupation',
        description: 'Must be an artisan, craftsperson, or traditional worker engaged in a recognized craft/trade',
        field: 'occupation',
        value: 'artisan',
      },
      {
        criterion: 'Annual Family Income',
        description: 'Annual family income must not exceed ₹5,00,000',
        field: 'annualFamilyIncome',
        value: 500000,
      },
      {
        criterion: 'Project Cost',
        description: 'Total project cost must be up to ₹2,00,000',
        field: 'estimatedProjectCost',
        value: 200000,
      },
    ],
    financialDetails: {
      maxLoanAmount: 180000,
      maxProjectCost: 200000,
      interestRate: 6,
      interestRateNote: '6% p.a. for SC artisans and craftspersons',
      repaymentPeriod: '3 years, quarterly instalments',
      repaymentPeriodMonths: 36,
      moratorium: '3 months',
      moratoriumMonths: 3,
      coverage: '90% of project cost',
      interestDuringMoratorium: null,
    },
    requiredDocuments: [
      'Scheduled Caste certificate issued by competent authority',
      'Income certificate (annual family income ≤ ₹5,00,000)',
      'Identity proof (Aadhaar Card / Voter ID / PAN Card)',
      'Address proof',
      'Artisan/craft identity card (if available)',
      'Details of craft/trade activity',
      'Quotations for tools/equipment/raw materials',
      'Bank account details',
      'Passport-size photographs',
    ],
    officialSource: {
      organization: 'NSFDC',
      url: 'https://nsfdc.nic.in/scheme',
      lastVerified: '2026-09-21',
    },
    channelPartnerTypes: [
      'State Channelizing Agencies (SCAs)',
      'Public Sector Banks (PSBs)',
    ],
  },
];
